print('RUN CIRCLE CI')

voucher_cost
voucher_cost_AGE 
voucher_cost_M_T180_VMVMP_TOTAL_SPEND
voucher_cost_notiopened2week
voucher_cost_notiopened1month
voucher_cost_voucher2week
voucher_cost_voucher1month
voucher_cost_order2week
voucher_cost_order1month
promotion_detail_absolute_discount_power_2
promotion_detail_percentage_discount_power_2
promotion_detail_discount_cap_max_power_2
promotion_detail_order_value_cap_min_power_2
promotion_detail_absolute_discount
promotion_detail_order_value_cap_min
promotion_detail_percentage_discount
promotion_detail_discount_cap_max
content_detail_promote_type_percentage_discount
content_detail_promote_type_absolute_discount
content_detail_promote_type_freeship_discount
content_detail_promote_type_no_promotion
GENDER
AGE