version: 2.1
jobs:
  build:
    working_directory: ~/root
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run: python --version
      - run: pip --version
      - run: |
          pip install -r requirements.txt
      - run: |
          python test.py