version: 2.1
jobs:
    build:
        working_directory: ~/root
        docker:
            - image: circleci/python:3.8.5
        steps:
            - checkout
            - run:
                  name: "python version"
                  command: |
                      python --version
            - run:
                  name: "pip version"
                  command: |
                      pip --version
            - run:
                  name: "install package"
                  command: |
                      pip install -r requirements.txt
            - run:
                  name: "python test"
                  command: |
                      python test.py
            - store_test_results:
                path: ~/root/autotonne
            - store_artifacts:
                path: ~/root/autotonne
    test:
        working_directory: ~/root
        docker:
            - image: circleci/python:3.9.0
        steps:
            - checkout
            - run:
                  name: "install package"
                  command: |
                      pip install -r requirements.txt
            - run:
                  name: "run test"
                  command: |
                      python test.py
            - store_test_results:
                path: ~/root/autotonne
            - store_artifacts:
                path: ~/root/autotonne

workflows:
    workflow:
        jobs:
            - build
            - test
